### ISSUE TITLE
MathJax and other scripts not loading via HTTPS

### ISSUE THREAD

**Issue by phiresky** [scottsievert/scottsievert.github.io#1]
Using HTTPS Everywhere enables https for  your website and makes the Tex sources show through (like `$x-1$`), see here: https://scottsievert.github.io/blog/2015/04/23/image-sqrt/

You should replace the `http://url` script references with `//url`
[errors screenshot](http://i.imgur.com/dzzS5hq.png)

**Comment by scottsievert** [comment]
Fixed.

To be clear, in `source/includes/custom/head.html` I changed 

```html
<!-- path: source/includes/custom/head.html -->
<link href='href://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>

<!-- path: source/layouts/default.html -->
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML" type="text/javascript"></script>
```

to

```html
<!-- path: source/includes/custom/head.html -->
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>

<!-- path: source/layouts/default.html -->
<script src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML" type="text/javascript"></script>
```

All I had to do was remove the `http:` but [the MathJax FAQ] helped.

[the MathJax FAQ]:http://docs.mathjax.org/en/latest/misc/faq.html#how-do-i-access-the-mathjax-cdn-using-a-https-secure-connection
